In [1]:
import pandas as pd

meta = pd.read_csv('/projects/bodymaps/Data/UCSFLLMOutputLarge27k.csv')

/local/psalvad2/875827/ipykernel_2533745/2667273785.py:3: DtypeWarning: Columns (11,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv('/projects/bodymaps/Data/UCSFLLMOutputLarge27k.csv')

In [2]:
meta

,Encrypted Patient MRN,Tumor ID,Organ,Tumor Type,Tumor Location,Tumor Size (mm),Tumor Attenuation,Type Certainty,DNN Answer,Report,...,Standardized Attenuation,Standardized Organ,Unknow Tumor Size,Standardized Location,BDMAP_ID,Patient Age,Patient Sex,no lesion,Index,Mapped Attenuation
0,AQPHRXY1,tumor 1,kidney,u,perinephric,5.0,low,u,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,kidney,no,u,BDMAP_00038206,69.0,Female,False,NaN,NaN
1,x0rEVlgI,tumor 1,kidney,u,u,9.0,hypodense,u,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,kidney,no,u,BDMAP_00041303,66.0,Female,False,NaN,NaN
2,x0rEVlgI,tumor 2,spleen,cyst,u,u,hypodense,high,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,spleen,yes,NaN,BDMAP_00041303,66.0,Female,False,NaN,NaN
3,ZLND5q9x,tumor 1,liver,metastasis,right lobe,u,hypoattenuating,low,Answer (template filled):\n\ntumor 1: type = m...,INTERPRETATION OF OUTSIDE [ADDRESS] ABDOMEN AN...,...,low,liver,yes,segment 5 / segment 6 / segment 7 / segment 8,NaN,62.0,Female,False,NaN,NaN
4,ZLND5q9x,tumor 2,liver,metastasis,right lobe,u,hypoattenuating,low,Answer (template filled):\n\ntumor 1: type = m...,INTERPRETATION OF OUTSIDE [ADDRESS] ABDOMEN AN...,...,low,liver,yes,segment 5 / segment 6 / segment 7 / segment 8,NaN,62.0,Female,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96846,NaN,tumor 2,liver,metastasis,u,13.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,liver,yes,u,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96847,NaN,tumor 3,liver,metastasis,u,multiple,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,liver,yes,u,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96848,NaN,tumor 4,bone,metastasis,vertebral body of l1,22.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,bone,no,NaN,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96849,NaN,tumor 5,bone,metastasis,right lower rib,11.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,bone,no,NaN,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96850,NaN,tumor 1,pancreas,pancreatic ductal adenocarcinoma (pdac),head,41.0 x 45.0 x 56.0,hypoenhancing,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,NaN,pancreas,no,head,BDMAP_00084952,NaN,NaN,NaN,221.0,low

In [3]:
def fill_location(row):
    # Check if the 'Tumor Location' is NaN or empty; if so, return 'u'
    if pd.isna(row['Tumor Location']):
        return 'u'
    # Convert the tumor location to lowercase to perform a case-insensitive check
    tumor_lower = row['Tumor Location'].lower()
    if 'right' in tumor_lower:
        return 'right'
    elif 'left' in tumor_lower:
        return 'left'
    else:
        return 'u'

# Create a mask for rows where Standardized Organ is "Adrenal Gland" (case insensitive)
mask = meta['Standardized Organ'].str.lower() == 'adrenal gland'

# Apply the function only on rows matching the mask
meta.loc[mask, 'Standardized Location'] = meta.loc[mask].apply(fill_location, axis=1)

In [4]:
for org in ['lung','breast','femur']:
    # Create a mask for rows where Standardized Organ is "Adrenal Gland" (case insensitive)
    mask = meta['Standardized Organ'].str.lower() == org

    # Apply the function only on rows matching the mask
    meta.loc[mask, 'Standardized Location'] = meta.loc[mask].apply(fill_location, axis=1)

In [5]:
meta[meta['BDMAP_ID']=='BDMAP_00080875']

,Encrypted Patient MRN,Tumor ID,Organ,Tumor Type,Tumor Location,Tumor Size (mm),Tumor Attenuation,Type Certainty,DNN Answer,Report,...,Standardized Attenuation,Standardized Organ,Unknow Tumor Size,Standardized Location,BDMAP_ID,Patient Age,Patient Sex,no lesion,Index,Mapped Attenuation
94091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT OF THE ABDOMEN AND PELVIS: [DATE].\r\n\r\nC...,...,NaN,NaN,NaN,NaN,BDMAP_00080875,45.0,Male,True,NaN,NaN

In [3]:

import numpy as np
#y = np.load('/projects/bodymaps/Data/UFO_27k_medformerNpz/BDMAP_00085207_gt.npz')['arr_0']
y = np.load('/projects/bodymaps/Pedro/data/UCSF_structured_report_subsegments_medformer_npz/BDMAP_00084817_gt.npz')['arr_0']

In [4]:
y.shape

(35, 435, 267, 403)

In [20]:
#labels:
pth = '/projects/bodymaps/Pedro/data/UFO_medformer_npy/list/label_names.yaml'
import yaml
with open(pth, 'r') as f:
    classes_UFO = yaml.load(f, Loader=yaml.SafeLoader)
    #sort--we sorted when saving in nii2npy.py
    classes_UFO = sorted(classes_UFO)

In [21]:
len(classes_UFO)

35

In [15]:
classes_UFO.index('spleen')

33

In [23]:
y[classes_UFO.index('adrenal_gland_left')].max()

1

In [24]:
# Assuming your DataFrame is named df
meta.drop("Unnamed: 0", axis=1, inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [8]:
meta

,Encrypted Patient MRN,Tumor ID,Organ,Tumor Type,Tumor Location,Tumor Size (mm),Tumor Attenuation,Type Certainty,DNN Answer,Report,...,Standardized Attenuation,Standardized Organ,Unknow Tumor Size,Standardized Location,BDMAP_ID,Patient Age,Patient Sex,no lesion,Index,Mapped Attenuation
0,AQPHRXY1,tumor 1,kidney,u,perinephric,5.0,low,u,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,kidney,no,u,BDMAP_00038206,69.0,Female,False,NaN,NaN
1,x0rEVlgI,tumor 1,kidney,u,u,9.0,hypodense,u,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,kidney,no,u,BDMAP_00041303,66.0,Female,False,NaN,NaN
2,x0rEVlgI,tumor 2,spleen,cyst,u,u,hypodense,high,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,spleen,yes,NaN,BDMAP_00041303,66.0,Female,False,NaN,NaN
3,ZLND5q9x,tumor 1,liver,metastasis,right lobe,u,hypoattenuating,low,Answer (template filled):\n\ntumor 1: type = m...,INTERPRETATION OF OUTSIDE [ADDRESS] ABDOMEN AN...,...,low,liver,yes,segment 5 / segment 6 / segment 7 / segment 8,NaN,62.0,Female,False,NaN,NaN
4,ZLND5q9x,tumor 2,liver,metastasis,right lobe,u,hypoattenuating,low,Answer (template filled):\n\ntumor 1: type = m...,INTERPRETATION OF OUTSIDE [ADDRESS] ABDOMEN AN...,...,low,liver,yes,segment 5 / segment 6 / segment 7 / segment 8,NaN,62.0,Female,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96846,NaN,tumor 2,liver,metastasis,u,13.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,liver,yes,u,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96847,NaN,tumor 3,liver,metastasis,u,multiple,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,liver,yes,u,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96848,NaN,tumor 4,bone,metastasis,vertebral body of l1,22.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,bone,no,NaN,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96849,NaN,tumor 5,bone,metastasis,right lower rib,11.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,bone,no,NaN,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96850,NaN,tumor 1,pancreas,pancreatic ductal adenocarcinoma (pdac),head,41.0 x 45.0 x 56.0,hypoenhancing,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,NaN,pancreas,no,head,BDMAP_00084952,NaN,NaN,NaN,221.0,low

In [1]:
import pandas as pd
meta = pd.read_csv('/projects/bodymaps/Data/UCSFLLMOutputLarge27k.csv')

/tmp/ipykernel_1664871/1566170393.py:2: DtypeWarning: Columns (11,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv('/projects/bodymaps/Data/UCSFLLMOutputLarge27k.csv')

In [2]:
meta

,Encrypted Patient MRN,Tumor ID,Organ,Tumor Type,Tumor Location,Tumor Size (mm),Tumor Attenuation,Type Certainty,DNN Answer,Report,...,Standardized Attenuation,Standardized Organ,Unknow Tumor Size,Standardized Location,BDMAP_ID,Patient Age,Patient Sex,no lesion,Index,Mapped Attenuation
0,AQPHRXY1,tumor 1,kidney,u,perinephric,5.0,low,u,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,kidney,no,u,BDMAP_00038206,69.0,Female,False,NaN,NaN
1,x0rEVlgI,tumor 1,kidney,u,u,9.0,hypodense,u,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,kidney,no,u,BDMAP_00041303,66.0,Female,False,NaN,NaN
2,x0rEVlgI,tumor 2,spleen,cyst,u,u,hypodense,high,Answer (template filled):\n\ntumor 1: type = U...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,low,spleen,yes,NaN,BDMAP_00041303,66.0,Female,False,NaN,NaN
3,ZLND5q9x,tumor 1,liver,metastasis,right lobe,u,hypoattenuating,low,Answer (template filled):\n\ntumor 1: type = m...,INTERPRETATION OF OUTSIDE [ADDRESS] ABDOMEN AN...,...,low,liver,yes,segment 5 / segment 6 / segment 7 / segment 8,NaN,62.0,Female,False,NaN,NaN
4,ZLND5q9x,tumor 2,liver,metastasis,right lobe,u,hypoattenuating,low,Answer (template filled):\n\ntumor 1: type = m...,INTERPRETATION OF OUTSIDE [ADDRESS] ABDOMEN AN...,...,low,liver,yes,segment 5 / segment 6 / segment 7 / segment 8,NaN,62.0,Female,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96846,NaN,tumor 2,liver,metastasis,u,13.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,liver,yes,u,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96847,NaN,tumor 3,liver,metastasis,u,multiple,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,liver,yes,u,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96848,NaN,tumor 4,bone,metastasis,vertebral body of l1,22.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,bone,no,NaN,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96849,NaN,tumor 5,bone,metastasis,right lower rib,11.0,u,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH AND WITH...,...,NaN,bone,no,NaN,BDMAP_00085075,NaN,NaN,NaN,332.0,u
96850,NaN,tumor 1,pancreas,pancreatic ductal adenocarcinoma (pdac),head,41.0 x 45.0 x 56.0,hypoenhancing,high,Answer (template filled):\n\ntumor 1: type = P...,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,NaN,pancreas,no,head,BDMAP_00084952,NaN,NaN,NaN,221.0,low

In [3]:
meta[meta['no lesion'] == True]

,Encrypted Patient MRN,Tumor ID,Organ,Tumor Type,Tumor Location,Tumor Size (mm),Tumor Attenuation,Type Certainty,DNN Answer,Report,...,Standardized Attenuation,Standardized Organ,Unknow Tumor Size,Standardized Location,BDMAP_ID,Patient Age,Patient Sex,no lesion,Index,Mapped Attenuation
92288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,NaN,NaN,NaN,NaN,BDMAP_00081037,40.0,Female,True,NaN,NaN
92289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN PEL W/CONTRAST [DATE]:42 PM\r\n\r\n...,...,NaN,NaN,NaN,NaN,BDMAP_00081203,57.0,Male,True,NaN,NaN
92290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Renal protocol CT scan [DATE]\r\n\r\nClinical ...,...,NaN,NaN,NaN,NaN,BDMAP_00081349,65.0,Male,True,NaN,NaN
92291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN PEL W/CONTRAST [DATE]:52 AM\r\n\r\n...,...,NaN,NaN,NaN,NaN,BDMAP_00080388,49.0,Male,True,NaN,NaN
92292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INDICATION:\r\nCT ABDOMEN/PELVIS WITH CONTRAST...,...,NaN,NaN,NaN,NaN,BDMAP_00080078,33.0,Female,True,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:14 P...,...,NaN,NaN,NaN,NaN,BDMAP_00033916,NaN,NaN,True,NaN,NaN
94853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:38 A...,...,NaN,NaN,NaN,NaN,BDMAP_00033917,NaN,NaN,True,NaN,NaN
94854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:29 AM_...,...,NaN,NaN,NaN,NaN,BDMAP_00033918,NaN,NaN,True,NaN,NaN
94855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:03 AM_...,...,NaN,NaN,NaN,NaN,BDMAP_00033921,NaN,NaN,True,NaN,NaN
94856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT ABDOMEN/PELVIS WITH CONTRAST [DATE]:43 A...,...,NaN,NaN,NaN,NaN,BDMAP_00033923,NaN,NaN,True,NaN,NaN

In [17]:
annotated_tumors = ['adrenal gland', 'bladder', 'colon', 'duodenum',
                    'esophagus', 'gallbladder','prostate','spleen','stomach']

def clean_ufo(reports):
    """
    This function gets a list of reports and removes cases of no interest:
    - We get the healthy patients
    - We get, for each tumor we have annotated organs, all reports that have known tumor size
    - We remove, for organs that have rignr and left (adrenal glands, kidneys), the reports that have unknown sub-segment (not right or left)
    Then, we print the number of useful cases per tumor
    """
    
    interest = {}
    
    for organ in annotated_tumors:
        interest[organ] = reports[reports['Standardized Organ'] == organ]
        interest[organ] = interest[organ][interest[organ]['Tumor Size (mm)'] != 'u']
        interest[organ] = interest[organ][interest[organ]['Tumor Size (mm)'] != 'multiple']
        interest[organ] = interest[organ][interest[organ]['Unknow Tumor Size'] == 'no']
        if organ in ['kidney','adrenal_gland','lung','breast','femur']:
            interest[organ] = interest[organ][interest[organ]['Standardized Location'].str.contains('right') | interest[organ]['Standardized Location'].str.contains('left')]
        print('Number of useful cases for %s: %s'%(organ, interest[organ]['BDMAP_ID'].nunique()))

    interest['healthy'] = reports[reports['no lesion'] == True]
    print('Number of healthy cases:', interest['healthy']['BDMAP_ID'].nunique())
    #concat
    interest = pd.concat(interest.values())
    interest = interest.drop_duplicates()
    print('Total number of useful cases:', interest['BDMAP_ID'].nunique())
    ids_of_interest = interest['BDMAP_ID'].unique().tolist()
    return interest, ids_of_interest

In [18]:
cleaned,ids = clean_ufo(meta)

Number of useful cases for adrenal gland: 1958
Number of useful cases for bladder: 929
Number of useful cases for colon: 672
Number of useful cases for duodenum: 419
Number of useful cases for esophagus: 155
Number of useful cases for gallbladder: 377
Number of useful cases for prostate: 473
Number of useful cases for spleen: 1475
Number of useful cases for stomach: 713
Number of healthy cases: 2569
Total number of useful cases: 9167

In [19]:
ids

['BDMAP_00038682',
 'BDMAP_00038831',
 'BDMAP_00044694',
 'BDMAP_00041758',
 'BDMAP_00041030',
 'BDMAP_00045068',
 'BDMAP_00044532',
 'BDMAP_00038022',
 'BDMAP_00038673',
 'BDMAP_00045133',
 'BDMAP_00038225',
 'BDMAP_00038870',
 'BDMAP_00044407',
 'BDMAP_00045595',
 'BDMAP_00040442',
 'BDMAP_00038717',
 'BDMAP_00045645',
 'BDMAP_00038792',
 'BDMAP_00045617',
 'BDMAP_00045373',
 'BDMAP_00038134',
 'BDMAP_00037179',
 'BDMAP_00039356',
 'BDMAP_00045886',
 'BDMAP_00046033',
 'BDMAP_00040887',
 'BDMAP_00041323',
 'BDMAP_00038176',
 'BDMAP_00036978',
 'BDMAP_00039647',
 nan,
 'BDMAP_00045631',
 'BDMAP_00038746',
 'BDMAP_00038362',
 'BDMAP_00045984',
 'BDMAP_00041756',
 'BDMAP_00041606',
 'BDMAP_00045729',
 'BDMAP_00037389',
 'BDMAP_00038604',
 'BDMAP_00041048',
 'BDMAP_00046042',
 'BDMAP_00037957',
 'BDMAP_00038223',
 'BDMAP_00045682',
 'BDMAP_00045688',
 'BDMAP_00037962',
 'BDMAP_00045932',
 'BDMAP_00045521',
 'BDMAP_00038076',
 'BDMAP_00038327',
 'BDMAP_00041408',
 'BDMAP_00045429',
 'BDMAP_00039382',
 'BDMAP_00042634',
 'BDMAP_00038713',
 'BDMAP_00044533',
 'BDMAP_00041955',
 'BDMAP_00041531',
 'BDMAP_00041406',
 'BDMAP_00039470',
 'BDMAP_00038116',
 'BDMAP_00041908',
 'BDMAP_00038858',
 'BDMAP_00041666',
 'BDMAP_00038075',
 'BDMAP_00041034',
 'BDMAP_00039613',
 'BDMAP_00039795',
 'BDMAP_00041368',
 'BDMAP_00037842',
 'BDMAP_00039289',
 'BDMAP_00040966',
 'BDMAP_00040957',
 'BDMAP_00038693',
 'BDMAP_00039477',
 'BDMAP_00039032',
 'BDMAP_00041127',
 'BDMAP_00039022',
 'BDMAP_00038969',
 'BDMAP_00043333',
 'BDMAP_00043055',
 'BDMAP_00041496',
 'BDMAP_00041003',
 'BDMAP_00039857',
 'BDMAP_00041529',
 'BDMAP_00039713',
 'BDMAP_00037886',
 'BDMAP_00039598',
 'BDMAP_00043308',
 'BDMAP_00042917',
 'BDMAP_00039637',
 'BDMAP_00035666',
 'BDMAP_00039248',
 'BDMAP_00042336',
 'BDMAP_00039073',
 'BDMAP_00042433',
 'BDMAP_00038897',
 'BDMAP_00039305',
 'BDMAP_00039528',
 'BDMAP_00039188',
 'BDMAP_00039803',
 'BDMAP_00042967',
 'BDMAP_00041831',
 'BDMAP_00039145',
 'BDMAP_00039083',
 'BDMAP_00042926',
 'BDMAP_00043334',
 'BDMAP_00043446',
 'BDMAP_00043082',
 'BDMAP_00039849',
 'BDMAP_00039402',
 'BDMAP_00042920',
 'BDMAP_00037568',
 'BDMAP_00035807',
 'BDMAP_00039236',
 'BDMAP_00038972',
 'BDMAP_00037879',
 'BDMAP_00039810',
 'BDMAP_00038978',
 'BDMAP_00042892',
 'BDMAP_00043457',
 'BDMAP_00041922',
 'BDMAP_00043289',
 'BDMAP_00042902',
 'BDMAP_00042172',
 'BDMAP_00038904',
 'BDMAP_00039390',
 'BDMAP_00039498',
 'BDMAP_00043251',
 'BDMAP_00039271',
 'BDMAP_00042251',
 'BDMAP_00043353',
 'BDMAP_00037757',
 'BDMAP_00043454',
 'BDMAP_00041833',
 'BDMAP_00042808',
 'BDMAP_00039484',
 'BDMAP_00039684',
 'BDMAP_00039846',
 'BDMAP_00043313',
 'BDMAP_00039276',
 'BDMAP_00039408',
 'BDMAP_00038935',
 'BDMAP_00042825',
 'BDMAP_00042973',
 'BDMAP_00037367',
 'BDMAP_00039109',
 'BDMAP_00037838',
 'BDMAP_00037326',
 'BDMAP_00042773',
 'BDMAP_00039331',
 'BDMAP_00039762',
 'BDMAP_00042615',
 'BDMAP_00042338',
 'BDMAP_00043144',
 'BDMAP_00044493',
 'BDMAP_00043436',
 'BDMAP_00038697',
 'BDMAP_00037502',
 'BDMAP_00036494',
 'BDMAP_00042782',
 'BDMAP_00036236',
 'BDMAP_00037151',
 'BDMAP_00037918',
 'BDMAP_00036513',
 'BDMAP_00036731',
 'BDMAP_00042123',
 'BDMAP_00037106',
 'BDMAP_00037907',
 'BDMAP_00042885',
 'BDMAP_00042352',
 'BDMAP_00042155',
 'BDMAP_00038374',
 'BDMAP_00043183',
 'BDMAP_00042142',
 'BDMAP_00036396',
 'BDMAP_00038544',
 'BDMAP_00038672',
 'BDMAP_00038375',
 'BDMAP_00042936',
 'BDMAP_00036202',
 'BDMAP_00038340',
 'BDMAP_00036567',
 'BDMAP_00038610',
 'BDMAP_00044041',
 'BDMAP_00036866',
 'BDMAP_00043686',
 'BDMAP_00038197',
 'BDMAP_00038878',
 'BDMAP_00036544',
 'BDMAP_00036835',
 'BDMAP_00036366',
 'BDMAP_00036678',
 'BDMAP_00036247',
 'BDMAP_00040781',
 'BDMAP_00040729',
 'BDMAP_00043806',
 'BDMAP_00036578',
 'BDMAP_00036082',
 'BDMAP_00040083',
 'BDMAP_00037781',
 'BDMAP_00040334',
 'BDMAP_00044266',
 'BDMAP_00037055',
 'BDMAP_00043667',
 'BDMAP_00037550',
 'BDMAP_00035456',
 'BDMAP_00037690',
 'BDMAP_00037313',
 'BDMAP_00044098',
 'BDMAP_00037785',
 'BDMAP_00037689',
 'BDMAP_00037050',
 'BDMAP_00043785',
 'BDMAP_00044277',
 'BDMAP_00043962',
 'BDMAP_00044157',
 'BDMAP_00044234',
 'BDMAP_00041741',
 'BDMAP_00043533',
 'BDMAP_00043031',
 'BDMAP_00040975',
 'BDMAP_00041239',
 'BDMAP_00041459',
 'BDMAP_00043943',
 'BDMAP_00041721',
 'BDMAP_00041627',
 'BDMAP_00037188',
 'BDMAP_00041381',
 'BDMAP_00044372',
 'BDMAP_00043768',
 'BDMAP_00037347',
 'BDMAP_00037587',
 'BDMAP_00041125',
 'BDMAP_00037480',
 'BDMAP_00040891',
 'BDMAP_00038839',
 'BDMAP_00038195',
 'BDMAP_00038289',
 'BDMAP_00035524',
 'BDMAP_00040921',
 'BDMAP_00038177',
 'BDMAP_00044366',
 'BDMAP_00041263',
 'BDMAP_00041390',
 'BDMAP_00041360',
 'BDMAP_00044006',
 'BDMAP_00038008',
 'BDMAP_00041754',
 'BDMAP_00038066',
 'BDMAP_00038504',
 'BDMAP_00037919',
 'BDMAP_00040906',
 'BDMAP_00044093',
 'BDMAP_00038875',
 'BDMAP_00041035',
 'BDMAP_00041736',
 'BDMAP_00040908',
 'BDMAP_00041735',
 'BDMAP_00038337',
 'BDMAP_00038488',
 'BDMAP_00042587',
 'BDMAP_00042442',
 'BDMAP_00043779',
 'BDMAP_00043455',
 'BDMAP_00041491',
 'BDMAP_00041715',
 'BDMAP_00042645',
 'BDMAP_00045374',
 'BDMAP_00041359',
 'BDMAP_00042690',
 'BDMAP_00038192',
 'BDMAP_00042443',
 'BDMAP_00038413',
 'BDMAP_00038280',
 'BDMAP_00042089',
 'BDMAP_00041424',
 'BDMAP_00041011',
 'BDMAP_00038300',
 'BDMAP_00038381',
 'BDMAP_00040944',
 'BDMAP_00042939',
 'BDMAP_00041041',
 'BDMAP_00039213',
 'BDMAP_00038086',
 'BDMAP_00045185',
 'BDMAP_00038595',
 'BDMAP_00041230',
 'BDMAP_00041186',
 'BDMAP_00041893',
 'BDMAP_00042855',
 'BDMAP_00039698',
 'BDMAP_00042315',
 'BDMAP_00038911',
 'BDMAP_00039403',
 'BDMAP_00042702',
 'BDMAP_00041711',
 'BDMAP_00040918',
 'BDMAP_00039346',
 'BDMAP_00041306',
 'BDMAP_00043179',
 'BDMAP_00043714',
 'BDMAP_00039055',
 'BDMAP_00040629',
 'BDMAP_00041661',
 'BDMAP_00044289',
 'BDMAP_00040679',
 'BDMAP_00039012',
 'BDMAP_00039556',
 'BDMAP_00039226',
 'BDMAP_00041231',
 'BDMAP_00041060',
 'BDMAP_00043564',
 'BDMAP_00039157',
 'BDMAP_00041383',
 'BDMAP_00044319',
 'BDMAP_00040226',
 'BDMAP_00039039',
 'BDMAP_00040120',
 'BDMAP_00040409',
 'BDMAP_00044901',
 'BDMAP_00044104',
 'BDMAP_00042313',
 'BDMAP_00040692',
 'BDMAP_00036727',
 'BDMAP_00042482',
 'BDMAP_00040322',
 'BDMAP_00040299',
 'BDMAP_00040114',
 'BDMAP_00040611',
 'BDMAP_00036800',
 'BDMAP_00044474',
 'BDMAP_00036431',
 'BDMAP_00036682',
 'BDMAP_00040683',
 'BDMAP_00042308',
 'BDMAP_00036129',
 'BDMAP_00040268',
 'BDMAP_00036766',
 'BDMAP_00044670',
 'BDMAP_00042428',
 'BDMAP_00040039',
 'BDMAP_00036115',
 'BDMAP_00044509',
 'BDMAP_00042161',
 'BDMAP_00040551',
 'BDMAP_00036190',
 'BDMAP_00042250',
 'BDMAP_00043765',
 'BDMAP_00042448',
 'BDMAP_00036327',
 'BDMAP_00040403',
 'BDMAP_00043941',
 'BDMAP_00042611',
 'BDMAP_00040240',
 'BDMAP_00044127',
 'BDMAP_00044150',
 'BDMAP_00042523',
 'BDMAP_00040055',
 'BDMAP_00036770',
 'BDMAP_00042042',
 'BDMAP_00040641',
 'BDMAP_00040740',
 'BDMAP_00036636',
 'BDMAP_00036393',
 'BDMAP_00042055',
 'BDMAP_00040069',
 'BDMAP_00040625',
 'BDMAP_00036162',
 'BDMAP_00040212',
 'BDMAP_00036534',
 'BDMAP_00036382',
 'BDMAP_00043758',
 'BDMAP_00040035',
 'BDMAP_00042193',
 'BDMAP_00044411',
 'BDMAP_00036081',
 'BDMAP_00041958',
 'BDMAP_00036308',
 'BDMAP_00036350',
 'BDMAP_00042368',
 'BDMAP_00040539',
 'BDMAP_00045160',
 'BDMAP_00040768',
 'BDMAP_00040785',
 'BDMAP_00045680',
 'BDMAP_00040323',
 'BDMAP_00042626',
 'BDMAP_00040825',
 'BDMAP_00042617',
 'BDMAP_00040018',
 'BDMAP_00040817',
 'BDMAP_00040580',
 'BDMAP_00040172',
 'BDMAP_00042533',
 'BDMAP_00045668',
 'BDMAP_00039925',
 'BDMAP_00040131',
 'BDMAP_00040780',
 'BDMAP_00045446',
 'BDMAP_00042081',
 'BDMAP_00045553',
 'BDMAP_00045800',
 'BDMAP_00036855',
 'BDMAP_00040165',
 'BDMAP_00042106',
 'BDMAP_00036883',
 'BDMAP_00044318',
 'BDMAP_00040306',
 'BDMAP_00042698',
 'BDMAP_00042341',
 'BDMAP_00039934',
 'BDMAP_00042036',
 'BDMAP_00040389',
 'BDMAP_00040057',
 'BDMAP_00042219',
 'BDMAP_00042291',
 'BDMAP_00040530',
 'BDMAP_00041923',
 'BDMAP_00043857',
 'BDMAP_00039971',
 'BDMAP_00040045',
 'BDMAP_00044151',
 'BDMAP_00039917',
 'BDMAP_00043863',
 'BDMAP_00040671',
 'BDMAP_00044754',
 'BDMAP_00039910',
 'BDMAP_00045176',
 'BDMAP_00036069',
 'BDMAP_00044252',
 'BDMAP_00045619',
 'BDMAP_00040419',
 'BDMAP_00044059',
 'BDMAP_00036331',
 'BDMAP_00045411',
 'BDMAP_00040104',
 'BDMAP_00045462',
 'BDMAP_00036658',
 'BDMAP_00036438',
 'BDMAP_00040377',
 'BDMAP_00044190',
 'BDMAP_00036593',
 'BDMAP_00040724',
 'BDMAP_00040081',
 'BDMAP_00045725',
 'BDMAP_00045340',
 'BDMAP_00040595',
 'BDMAP_00045438',
 'BDMAP_00040695',
 'BDMAP_00040219',
 'BDMAP_00045563',
 'BDMAP_00040065',
 'BDMAP_00044067',
 'BDMAP_00045694',
 'BDMAP_00040828',
 'BDMAP_00045204',
 'BDMAP_00045937',
 'BDMAP_00044204',
 'BDMAP_00043917',
 'BDMAP_00043603',
 'BDMAP_00044652',
 'BDMAP_00043981',
 'BDMAP_00045113',
 'BDMAP_00045326',
 'BDMAP_00044052',
 'BDMAP_00044211',
 'BDMAP_00037244',
 'BDMAP_00037579',
 'BDMAP_00037555',
 'BDMAP_00045768',
 'BDMAP_00036172',
 'BDMAP_00044129',
 'BDMAP_00036693',
 'BDMAP_00040831',
 'BDMAP_00043993',
 'BDMAP_00043684',
 'BDMAP_00044423',
 'BDMAP_00036180',
 'BDMAP_00043881',
 'BDMAP_00037911',
 'BDMAP_00044729',
 'BDMAP_00037482',
 'BDMAP_00040777',
 'BDMAP_00040787',
 'BDMAP_00040599',
 'BDMAP_00037672',
 'BDMAP_00044990',
 'BDMAP_00037454',
 'BDMAP_00037522',
 'BDMAP_00044795',
 'BDMAP_00037219',
 'BDMAP_00037072',
 'BDMAP_00044766',
 'BDMAP_00037391',
 'BDMAP_00044864',
 'BDMAP_00037658',
 'BDMAP_00036137',
 'BDMAP_00037247',
 'BDMAP_00037804',
 'BDMAP_00044668',
 'BDMAP_00037181',
 'BDMAP_00044881',
 'BDMAP_00037025',
 'BDMAP_00037158',
 'BDMAP_00036838',
 'BDMAP_00040421',
 'BDMAP_00036161',
 'BDMAP_00044714',
 'BDMAP_00044800',
 'BDMAP_00045153',
 'BDMAP_00037418',
 'BDMAP_00043203',
 'BDMAP_00040547',
 'BDMAP_00045302',
 'BDMAP_00045296',
 'BDMAP_00036416',
 'BDMAP_00042987',
 'BDMAP_00036334',
 'BDMAP_00043697',
 'BDMAP_00045338',
 'BDMAP_00037549',
 'BDMAP_00045047',
 'BDMAP_00042983',
 'BDMAP_00037873',
 'BDMAP_00037319',
 'BDMAP_00037245',
 'BDMAP_00036744',
 'BDMAP_00037359',
 'BDMAP_00044753',
 'BDMAP_00037096',
 'BDMAP_00037432',
 'BDMAP_00037461',
 'BDMAP_00042775',
 'BDMAP_00037101',
 'BDMAP_00044826',
 'BDMAP_00036171',
 'BDMAP_00036140',
 'BDMAP_00037661',
 'BDMAP_00044995',
 'BDMAP_00037510',
 'BDMAP_00037192',
 'BDMAP_00036802',
 'BDMAP_00042882',
 'BDMAP_00037094',
 'BDMAP_00062899',
 'BDMAP_00045612',
 'BDMAP_00043261',
 'BDMAP_00037038',
 'BDMAP_00036519',
 'BDMAP_00043016',
 'BDMAP_00044487',
 'BDMAP_00036166',
 'BDMAP_00044835',
 'BDMAP_00037777',
 'BDMAP_00037136',
 'BDMAP_00044322',
 'BDMAP_00036376',
 'BDMAP_00040731',
 'BDMAP_00043087',
 'BDMAP_00037058',
 'BDMAP_00045442',
 'BDMAP_00037544',
 'BDMAP_00038457',
 'BDMAP_00038578',
 'BDMAP_00044242',
 'BDMAP_00044058',
 'BDMAP_00040958',
 'BDMAP_00045766',
 'BDMAP_00045568',
 'BDMAP_00044380',
 'BDMAP_00046060',
 'BDMAP_00043517',
 'BDMAP_00044370',
 'BDMAP_00038333',
 'BDMAP_00043565',
 'BDMAP_00043975',
 'BDMAP_00040181',
 'BDMAP_00045364',
 'BDMAP_00045673',
 'BDMAP_00045036',
 'BDMAP_00045482',
 'BDMAP_00045532',
 'BDMAP_00045352',
 'BDMAP_00045774',
 'BDMAP_00041352',
 'BDMAP_00043685',
 'BDMAP_00038700',
 'BDMAP_00041296',
 'BDMAP_00045572',
 'BDMAP_00043492',
 'BDMAP_00040845',
 'BDMAP_00045550',
 'BDMAP_00036174',
 'BDMAP_00045477',
 'BDMAP_00044867',
 'BDMAP_00041022',
 'BDMAP_00045758',
 'BDMAP_00044713',
 'BDMAP_00037925',
 'BDMAP_00041494',
 'BDMAP_00040991',
 'BDMAP_00045451',
 'BDMAP_00044665',
 'BDMAP_00036902',
 'BDMAP_00045933',
 'BDMAP_00045666',
 'BDMAP_00045332',
 'BDMAP_00045934',
 'BDMAP_00045582',
 'BDMAP_00045671',
 'BDMAP_00046032',
 'BDMAP_00044514',
 'BDMAP_00045554',
 'BDMAP_00041151',
 'BDMAP_00041668',
 'BDMAP_00046056',
 'BDMAP_00045652',
 'BDMAP_00038726',
 'BDMAP_00045394',
 'BDMAP_00038267',
 'BDMAP_00036338',
 'BDMAP_00038850',
 'BDMAP_00038382',
 'BDMAP_00041755',
 'BDMAP_00038827',
 'BDMAP_00041070',
 'BDMAP_00038807',
 'BDMAP_00038652',
 'BDMAP_00038660',
 'BDMAP_00038444',
 'BDMAP_00038331',
 'BDMAP_00036269',
 'BDMAP_00054481',
 'BDMAP_00055092',
 'BDMAP_00054622',
 'BDMAP_00055571',
 'BDMAP_00054770',
 'BDMAP_00054333',
 'BDMAP_00054339',
 'BDMAP_00055090',
 'BDMAP_00054948',
 'BDMAP_00054926',
 'BDMAP_00054344',
 'BDMAP_00056109',
 'BDMAP_00054394',
 'BDMAP_00049969',
 'BDMAP_00054717',
 'BDMAP_00054352',
 'BDMAP_00054684',
 'BDMAP_00054602',
 'BDMAP_00055775',
 'BDMAP_00054267',
 'BDMAP_00054958',
 'BDMAP_00054672',
 'BDMAP_00054980',
 'BDMAP_00054373',
 'BDMAP_00054975',
 'BDMAP_00054540',
 'BDMAP_00054247',
 'BDMAP_00054765',
 'BDMAP_00054507',
 'BDMAP_00054855',
 'BDMAP_00054274',
 'BDMAP_00055139',
 'BDMAP_00050156',
 'BDMAP_00054427',
 'BDMAP_00054396',
 'BDMAP_00062399',
 'BDMAP_00054894',
 'BDMAP_00054600',
 'BDMAP_00054817',
 'BDMAP_00054950',
 'BDMAP_00050652',
 'BDMAP_00054623',
 'BDMAP_00054711',
 'BDMAP_00054893',
 'BDMAP_00054422',
 'BDMAP_00035539',
 'BDMAP_00054963',
 'BDMAP_00051220',
 'BDMAP_00054937',
 'BDMAP_00054313',
 'BDMAP_00055082',
 'BDMAP_00054874',
 'BDMAP_00054400',
 'BDMAP_00054407',
 'BDMAP_00054841',
 'BDMAP_00054664',
 'BDMAP_00050474',
 'BDMAP_00054731',
 'BDMAP_00049445',
 'BDMAP_00049832',
 'BDMAP_00054538',
 'BDMAP_00055150',
 'BDMAP_00060797',
 'BDMAP_00054747',
 'BDMAP_00054539',
 'BDMAP_00054900',
 'BDMAP_00054241',
 'BDMAP_00054821',
 'BDMAP_00054749',
 'BDMAP_00055660',
 'BDMAP_00056463',
 'BDMAP_00054560',
 'BDMAP_00051089',
 'BDMAP_00055124',
 'BDMAP_00055078',
 'BDMAP_00051226',
 'BDMAP_00054329',
 'BDMAP_00054676',
 'BDMAP_00054852',
 'BDMAP_00054645',
 'BDMAP_00055073',
 'BDMAP_00054454',
 'BDMAP_00051313',
 'BDMAP_00054290',
 'BDMAP_00050203',
 'BDMAP_00054342',
 'BDMAP_00054567',
 'BDMAP_00054548',
 'BDMAP_00054434',
 'BDMAP_00055162',
 'BDMAP_00054990',
 'BDMAP_00054680',
 'BDMAP_00064173',
 'BDMAP_00054943',
 'BDMAP_00063932',
 'BDMAP_00051071',
 'BDMAP_00054812',
 'BDMAP_00056052',
 'BDMAP_00050930',
 'BDMAP_00061552',
 'BDMAP_00061004',
 'BDMAP_00054692',
 'BDMAP_00054415',
 'BDMAP_00054933',
 'BDMAP_00054524',
 'BDMAP_00051037',
 'BDMAP_00055043',
 'BDMAP_00061263',
 'BDMAP_00055054',
 'BDMAP_00050655',
 'BDMAP_00054591',
 'BDMAP_00054941',
 'BDMAP_00063951',
 'BDMAP_00055832',
 'BDMAP_00060925',
 'BDMAP_00054497',
 'BDMAP_00057310',
 'BDMAP_00063751',
 'BDMAP_00054440',
 'BDMAP_00050178',
 'BDMAP_00061502',
 'BDMAP_00054918',
 'BDMAP_00051045',
 'BDMAP_00060990',
 'BDMAP_00054766',
 'BDMAP_00049913',
 'BDMAP_00050705',
 'BDMAP_00057198',
 'BDMAP_00055472',
 'BDMAP_00054743',
 'BDMAP_00055132',
 'BDMAP_00054668',
 'BDMAP_00051057',
 'BDMAP_00055321',
 'BDMAP_00056024',
 'BDMAP_00055468',
 'BDMAP_00055375',
 'BDMAP_00054898',
 'BDMAP_00056035',
 'BDMAP_00054500',
 'BDMAP_00054883',
 'BDMAP_00054364',
 'BDMAP_00054412',
 'BDMAP_00051442',
 'BDMAP_00054861',
 'BDMAP_00054730',
 'BDMAP_00054491',
 'BDMAP_00054472',
 'BDMAP_00057466',
 'BDMAP_00054381',
 'BDMAP_00054593',
 'BDMAP_00054321',
 'BDMAP_00051025',
 'BDMAP_00054428',
 'BDMAP_00054486',
 'BDMAP_00064194',
 'BDMAP_00054493',
 'BDMAP_00050740',
 'BDMAP_00054470',
 'BDMAP_00055063',
 'BDMAP_00050368',
 'BDMAP_00054760',
 'BDMAP_00050473',
 'BDMAP_00054508',
 'BDMAP_00051030',
 'BDMAP_00050913',
 'BDMAP_00055742',
 'BDMAP_00054875',
 'BDMAP_00056053',
 'BDMAP_00055120',
 'BDMAP_00054906',
 'BDMAP_00050689',
 'BDMAP_00055795',
 'BDMAP_00054568',
 'BDMAP_00051497',
 'BDMAP_00054392',
 'BDMAP_00053702',
 'BDMAP_00055145',
 'BDMAP_00054655',
 'BDMAP_00055267',
 'BDMAP_00063786',
 'BDMAP_00054826',
 'BDMAP_00054662',
 'BDMAP_00055703',
 'BDMAP_00051001',
 'BDMAP_00055793',
 'BDMAP_00055918',
 'BDMAP_00050437',
 'BDMAP_00055052',
 'BDMAP_00050177',
 'BDMAP_00054534',
 'BDMAP_00054663',
 'BDMAP_00054613',
 'BDMAP_00055123',
 'BDMAP_00050918',
 'BDMAP_00051350',
 'BDMAP_00050780',
 'BDMAP_00055497',
 'BDMAP_00054938',
 'BDMAP_00054740',
 'BDMAP_00055845',
 'BDMAP_00054501',
 'BDMAP_00055285',
 'BDMAP_00064152',
 'BDMAP_00055018',
 'BDMAP_00050279',
 'BDMAP_00057765',
 'BDMAP_00063801',
 'BDMAP_00055678',
 'BDMAP_00051164',
 'BDMAP_00055067',
 'BDMAP_00054675',
 'BDMAP_00057385',
 'BDMAP_00050726',
 'BDMAP_00055843',
 'BDMAP_00063901',
 'BDMAP_00056054',
 'BDMAP_00054751',
 'BDMAP_00051273',
 'BDMAP_00051484',
 'BDMAP_00055630',
 'BDMAP_00055056',
 'BDMAP_00050852',
 'BDMAP_00058002',
 'BDMAP_00055502',
 'BDMAP_00055080',
 'BDMAP_00054449',
 'BDMAP_00060913',
 'BDMAP_00054462',
 'BDMAP_00063922',
 'BDMAP_00061322',
 'BDMAP_00057174',
 'BDMAP_00054678',
 'BDMAP_00061781',
 'BDMAP_00050199',
 'BDMAP_00054388',
 'BDMAP_00057879',
 'BDMAP_00055518',
 'BDMAP_00054886',
 'BDMAP_00054516',
 'BDMAP_00057841',
 'BDMAP_00054928',
 'BDMAP_00051061',
 'BDMAP_00055016',
 'BDMAP_00061258',
 'BDMAP_00055014',
 'BDMAP_00057547',
 'BDMAP_00056056',
 'BDMAP_00054723',
 'BDMAP_00054648',
 'BDMAP_00054719',
 'BDMAP_00051242',
 'BDMAP_00061182',
 'BDMAP_00055324',
 'BDMAP_00054902',
 'BDMAP_00054386',
 'BDMAP_00054571',
 'BDMAP_00051021',
 'BDMAP_00055025',
 'BDMAP_00055981',
 'BDMAP_00061745',
 'BDMAP_00054795',
 'BDMAP_00051323',
 'BDMAP_00054627',
 'BDMAP_00051134',
 'BDMAP_00050761',
 'BDMAP_00051138',
 'BDMAP_00055351',
 'BDMAP_00054487',
 'BDMAP_00051223',
 'BDMAP_00063733',
 'BDMAP_00054631',
 'BDMAP_00056077',
 'BDMAP_00051190',
 'BDMAP_00050938',
 'BDMAP_00057165',
 'BDMAP_00055691',
 'BDMAP_00055905',
 'BDMAP_00055055',
 'BDMAP_00055191',
 'BDMAP_00050894',
 'BDMAP_00060936',
 'BDMAP_00055640',
 'BDMAP_00055935',
 'BDMAP_00061209',
 'BDMAP_00055312',
 'BDMAP_00054683',
 'BDMAP_00051222',
 'BDMAP_00057442',
 'BDMAP_00051338',
 'BDMAP_00051041',
 'BDMAP_00049935',
 'BDMAP_00051132',
 'BDMAP_00055856',
 'BDMAP_00055777',
 'BDMAP_00054805',
 'BDMAP_00055815',
 'BDMAP_00055277',
 'BDMAP_00055861',
 'BDMAP_00055335',
 'BDMAP_00055936',
 'BDMAP_00061315',
 'BDMAP_00050948',
 'BDMAP_00055713',
 'BDMAP_00053684',
 'BDMAP_00051184',
 'BDMAP_00050984',
 'BDMAP_00055044',
 'BDMAP_00050946',
 'BDMAP_00050773',
 'BDMAP_00052617',
 'BDMAP_00051509',
 'BDMAP_00055283',
 'BDMAP_00055287',
 'BDMAP_00050862',
 'BDMAP_00054995',
 'BDMAP_00051731',
 'BDMAP_00055169',
 'BDMAP_00051405',
 'BDMAP_00054644',
 'BDMAP_00054417',
 'BDMAP_00054595',
 'BDMAP_00050910',
 'BDMAP_00050683',
 'BDMAP_00054546',
 'BDMAP_00055165',
 'BDMAP_00054601',
 'BDMAP_00064073',
 'BDMAP_00052047',
 'BDMAP_00050663',
 'BDMAP_00055402',
 'BDMAP_00055746',
 'BDMAP_00056628',
 'BDMAP_00051775',
 'BDMAP_00052926',
 'BDMAP_00057444',
 'BDMAP_00055698',
 'BDMAP_00057376',
 'BDMAP_00050743',
 'BDMAP_00055709',
 'BDMAP_00053101',
 'BDMAP_00053149',
 'BDMAP_00062340',
 'BDMAP_00056159',
 'BDMAP_00056397',
 'BDMAP_00050882',
 'BDMAP_00052116',
 'BDMAP_00051425',
 'BDMAP_00051741',
 'BDMAP_00052808',
 'BDMAP_00055423',
 'BDMAP_00062201',
 'BDMAP_00056310',
 'BDMAP_00052266',
 'BDMAP_00052664',
 'BDMAP_00055395',
 'BDMAP_00052107',
 'BDMAP_00051872',
 'BDMAP_00057334',
 'BDMAP_00056715',
 'BDMAP_00056215',
 'BDMAP_00051749',
 'BDMAP_00056796',
 'BDMAP_00054872',
 'BDMAP_00051559',
 'BDMAP_00052289',
 ...]

In [20]:
len(ids)

9168

In [25]:

#check pdac
import numpy as np
y = np.load('/projects/bodymaps/Pedro/data/JHH_lesion_types_medformer_npz/BDMAP_V0001442_gt.npz')['arr_0']

In [26]:
#labels:
pth = '/projects/bodymaps/Pedro/data/JHH_lesion_types_medformer/list/label_names.yaml'
import yaml
with open(pth, 'r') as f:
    classes = yaml.load(f, Loader=yaml.SafeLoader)
    #sort--we sorted when saving in nii2npy.py
    classes = sorted(classes)

In [27]:
y[classes.index('pancreatic_pdac')].sum()

99694

In [28]:
y.shape

(45, 483, 306, 351)

In [29]:
y[classes.index('pancreatic_lesion')].sum()

99694

In [33]:

#check pdac
import numpy as np
y = np.load('/projects/bodymaps/Pedro/data/AbdomenAtlas3_JHH_medformer_augmented_balanced_crops_lesion_types/BDMAP_V0001442_gt.npy')
y = np.unpackbits(y, axis=0)[:45]

In [34]:
y.shape

(45, 128, 128, 128)

In [35]:
y[classes.index('pancreatic_lesion')].sum()

75329

In [36]:
y[classes.index('pancreatic_pdac')].sum()

75329